# Introduction to Matrices in Python Using NumPy

In [1]:
import numpy as np
import random

## Manually enter a 3x3 matrix

In [2]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 2x2 matrix using random numbers

In [3]:
T = np.random.randint(-2, 3, size = (2, 2))
T

array([[0, 2],
       [0, 1]])

## Particular Matrices

### Identity Matrix

In [4]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Zeros Matrix

In [5]:
Z = np.zeros((3, 3)) #argument must be a tuple
Z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Ones Matrix

In [6]:
O = np.ones((5, 4))
O

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Diagonal Matrix

In [7]:
D = np.diag([1, 2, 3])
D

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [8]:
C = np.diag(M) #will return an array
C

array([1, 5, 9])